# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 09:52
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('police_id', models.CharField(max_length=20)),
                ('designation', models.CharField(choices=[('DGP', 'Director General of Police'), ('ADGP', 'Addl. Director General of Police'), ('IGP', 'Inspector General of Police'), ('DIGP', 'Deputy Inspector General of Police'), ('SPDCP', 'Superintendent of police Deputy Commissioner of Police(Selection Grade)'), ('SPDCPJ', 'Superintendent of police Deputy Commissioner of Police(Junior Management Grade)'), ('ASPADCP', 'Addl. Superintendent of police Addl.Deputy Commissioner of Police'), ('ASP', 'Assistant Superintendent of Police'), ('INSP', 'Inspector of Police'), ('SUB_INSP', 'Sub Inspector of Police.'), ('HVLDRM', 'Asst. Sub. Inspector/Havildar Major'), ('HVLDR', 'Havildar.'), ('LN', 'Lance Naik.'), ('CONS', 'Constable.')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Police',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='police',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='police.Ward'),
        ),
        migrations.AddField(
            model_name='contact',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.Ward'),
        ),
    ]
