# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='id',
            field=models.CharField(choices=[('RJ14W01', 'Mansarovar'), ('RJ14W02', 'Jagatpura'), ('RJ14W03', 'Sanganer'), ('RJ14W04', 'Kachi Basti'), ('RJ14W05', 'Malviya Nagar'), ('RJ14W06', 'Bani Park'), ('RJ14W07', 'Sitapura'), ('RJ14W08', 'Raja Park'), ('RJ14W09', 'Triveni Nagar'), ('RJ14W10', 'Badi Chopat'), ('RJ14W11', 'Chandpole')], max_length=10, primary_key=True, serialize=False),
        ),
    ]
