# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=255)),
                ('caste', models.CharField(max_length=255)),
                ('birth_mark_desc', models.TextField()),
                ('height', models.CharField(max_length=255)),
                ('complexion', models.CharField(max_length=255)),
                ('eyes', models.CharField(max_length=255)),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='police.Ward')),
            ],
        ),
    ]
