# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoustip',
            name='incident_time',
            field=models.DateField(),
        ),
    ]
