# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, upload_to=home.models.image_upload_location)),
                ('image2', models.ImageField(blank=True, upload_to=home.models.image_upload_location)),
                ('doc', models.FileField(blank=True, upload_to=home.models.doc_upload_location)),
                ('video', models.FileField(blank=True, upload_to=home.models.doc_upload_location)),
            ],
        ),
        migrations.AddField(
            model_name='anonymoustip',
            name='upload_evidence',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
