# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171202_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoustip',
            name='upload_evidence',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
