# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence',
            field=models.ImageField(blank=True, upload_to=home.models.image_upload_location),
        ),
    ]
