# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='bhamshah',
            new_name='bhamashah',
        ),
    ]
