# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
