# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='bhamashah',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
