# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_auto_20171202_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
