# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_citizen_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='dob',
            new_name='birth_date',
        ),
    ]
