# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_case_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='approved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='solved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
