# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_case_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='ward_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.Ward'),
        ),
    ]
