# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_case_ward_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='approved',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='solved',
            field=models.NullBooleanField(),
        ),
    ]
