# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20171203_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.Citizen'),
        ),
    ]
