# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20171202_1924'),
        ('case', '0003_auto_20171202_1933'),
    ]

    operations = [
    ]
