# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20171202_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='incident_time',
            field=models.DateField(),
        ),
    ]
